# Generated by Django 3.0.7 on 2020-06-30 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_auto_20200630_0021'),
        ('cars', '0001_initial'),
        ('seg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('F', 'Fechada'), ('A', 'Aguardando Entrega'), ('V', 'Vencido'), ('N', 'Novo Aluguel')], db_column='de_status', default='N', max_length=30, null=True)),
                ('tipo', models.CharField(choices=[('D', 'Diaria'), ('S', 'Semana'), ('M', 'Mes')], db_column='tp_aluguel', max_length=30, null=True)),
                ('data_de_retirada', models.DateField(db_column='dt_retirada', null=True)),
                ('local_de_retira', models.CharField(db_column='local_retira', max_length=200)),
                ('data_de_devolucao', models.DateField(db_column='dt_devolucao', null=True)),
                ('valor_aluguel', models.IntegerField(db_column='lv_aluguel', null=True)),
                ('cupom', models.CharField(db_column='nm_cupom', max_length=30, null=True)),
                ('numero_contrato', models.CharField(db_column='nm_contrato', max_length=30, null=True)),
                ('observacao', models.TextField(blank=True, db_column='de_observacao', max_length=200, null=True)),
                ('cliente', models.ForeignKey(db_column='de_cliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='client.Client')),
                ('seguradora', models.ForeignKey(db_column='de_seguradora', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='seg.Seg')),
                ('veiculo', models.ForeignKey(db_column='de_veiculo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cars.Car')),
            ],
            options={
                'db_table': 'tb_locacao',
            },
        ),
    ]
