# Generated by Django 3.0.7 on 2020-06-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponibilidade', models.BooleanField(default=True, null=True)),
                ('placa', models.CharField(db_column='de_placa', max_length=7, null=True)),
                ('marca', models.CharField(choices=[('SD', 'Sea doo'), ('CH', 'Chevrolet'), ('FI', 'Fiat'), ('FO', 'Ford'), ('KW', 'Kawasaki'), ('VO', 'Volkswagen'), ('YA', 'Yamaha')], db_column='de_marca', max_length=120, null=True)),
                ('tipo', models.CharField(choices=[('JT', 'Jetski'), ('CA', 'Carro')], db_column='de_tipo', max_length=120, null=True)),
                ('data_fabricacao', models.DateField(db_column='data_fabricacao', max_length=4, null=True)),
                ('data_entrada', models.DateField(db_column='data_entrada', max_length=4, null=True)),
            ],
            options={
                'db_table': 'tb_veiculo',
            },
        ),
    ]
