# Generated by Django 3.0.7 on 2020-06-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='de_nome', max_length=120, null=True)),
                ('cnpj', models.CharField(db_column='de_cnpj', max_length=14, null=True)),
                ('email', models.EmailField(db_column='de_email', max_length=254, null=True)),
                ('telefone', models.CharField(db_column='nr_tel_celular', max_length=22, null=True)),
                ('tipo_de_seguro', models.CharField(choices=[('1', 'Total'), ('2', 'Danos'), ('3', 'Roubo'), ('4', 'Desastres')], db_column='de_tipo_seguradora', max_length=120, null=True)),
                ('id_contrato', models.CharField(db_column='de_contrato', max_length=30, null=True)),
            ],
            options={
                'db_table': 'tb_seguradora',
            },
        ),
    ]
